apiVersion: apps/v1
kind: Deployment
metadata:
  name: pro3-web
spec:
  selector:
    matchLabels:
      app: pro3-web
  replicas: 2
  template:
    metadata:
      labels:
        app: pro3-web
    spec:
      containers:
      - name: pro3-web
        image: 784695908961.dkr.ecr.us-west-2.amazonaws.com/nginx:dragon
        ports:
        - containerPort: 80
        env:
          - name: TOMCATS
            value: k8s-default-pro3apps-1bd24edb6b-c79084554ce23fed.elb.us-west-2.amazonaws.com
