apiVersion: apps/v1
kind: Deployment
metadata:
  name: pro3-web
spec:
  selector:
    matchLabels:
      app: pro3-web
  replicas: 1
  template:
    metadata: pro3-web-pod
      labels:
        app: pro3-web
    spec:
      containers:
      - name: pro3-web
        image: jinsu0625/pro3-nginx:dragon
        ports:
        - containerPort: 80
        env:
          - name: TOMCATS
            value: pro3-app-service
